### ISSUE TITLE
Heavy Debug Log Spam "Unable to resolve texture due to reference chain color->color"

### ISSUE THREAD

**Issue by RConTRS** [Nosiphus/nosiphus-furniture#10]
I Recently Made A Huge Modpack, And Decided To Include Your Mod, However There's Over 26K lines of log spam in the debug log
There's Also Frequent Lines From Quark
Well I Tried To Load The Game With Only CFM, NFM And Quark, Both Latest And Debug Logs Seems Good So I Think It's A Conflict With Other Mod, See What You Can Do Anyway, Maybe It's On Your Side

[Log.txt](https://github.com/Nosiphus/nosiphus-furniture-mod/files/10948598/Log.txt)
Minecraft Version : 1.19.2
Forge Version : 43.2.6
Mod Version : 11.23

**Comment by seancrain** [comment]
I'm working on rewriting the model files for the next update that should get rid of the logspam. It may take me a while to do this since there's a lot of stuff to rewrite, but they'll be fixed in the next update.

**Comment by seancrain** [comment]
This was fixed in the 2023.05.06 update.
