### ISSUE TITLE
Pickaxe blocks do not drop

### ISSUE THREAD

**Issue by Lukebb04** [Nosiphus/nosiphus-furniture#14]
this happens because pickaxe.json has blocks that are not in the game

**Comment by seancrain** [comment]
What version of the game are you playing, and which block are you trying to break? It seems to work correctly for me.

**Comment by Lukebb04** [comment]
stone with a pickaxe it takes longer and does not drop

**Comment by seancrain** [comment]
I am not seeing any problems with NFM and stone drops in the latest 1.19.2 build I shipped a couple days ago. Is this for a different version?

**Comment by Lukebb04** [comment]
im using 1.19.3
