### ISSUE TITLE
This mod and Iris

### ISSUE THREAD

**Issue by TeknoStyle555** [Nosiphus/nosiphus-furniture#16]
As the title suggests, there's an incompatibility issue when it comes to Iris.

Here's an image of what the error gave me.
![Screenshot (458)](https://github.com/Nosiphus/nosiphus-furniture-mod/assets/56555948/a0da7706-16c2-4957-ad45-1fc863da5c08)

And here's the crash report.
[crash-2023-06-30_12.48.36-client.txt](https://github.com/Nosiphus/nosiphus-furniture-mod/files/11915617/crash-2023-06-30_12.48.36-client.txt)

**Comment by seancrain** [comment]
The Nosiphus Furniture Mod was built against Forge 47.0.34 on 1.20.1, and the current version of Forge is 47.1.29. You are currently using 47.0.19. I've seen this issue where an incompatibility is detected but the correct screen isn't displayed. Update your Forge build as well as your other mods and that should fix the problem.

**Comment by TeknoStyle555** [comment]
Thanks, it works now.
