### ISSUE TITLE
It's all in Spanish?

### ISSUE THREAD

**Issue by DarkblooM-IO** [Nosiphus/nosiphus-furniture#23]
Items are named in Spanish, not sure if that's intentional.
It's not a major issue but I figured I should point it out.

**Comment by seancrain** [comment]
The en_US language file in the assets is definitely in English. The code itself does name the objects slightly differently, but not the registry names or the language file. Even with that said, none of them are in Spanish.

If you're seeing this in-game, is there another mod installed that might be translating it into Spanish? I don't have a Spanish language file defined so it certainly isn't that.
