### ISSUE TITLE
Soapy Water Crashes Client on Disconnect from Server

### ISSUE THREAD

**Issue by MadSciSlack** [Nosiphus/nosiphus-furniture#24]
Soapy water is not registered properly, but somehow referenced when disconnect from servers.  Please double check your item registrations.  I cannot guarantee that the other new items aren't also having issues, as the client crashes on the first one. 

https://pastebin.com/b4erTeKG

**Comment by seancrain** [comment]
I am attempting to replicate this in the development environment and it seems to be functioning normally. I've also had it installed on my own server alongside Canary, which is referenced further down in your crash report's listing, and I had no crashes occur. What did you do in-game to cause this?

If you're using a modpack, please let me know what it's called so I can test it with the full mods and see if I can find a conflict.

**Comment by MadSciSlack** [comment]
I just disconnected normally, which caused the client to crash unexpectedly.  I've not experienced it since, so I'm thinking this isn't something we're going to find the source of easily.  I'll update if it happens again, but this one is a mystery.
