### ISSUE TITLE
Deregistering Tools

### ISSUE THREAD

**Issue by thomwoosley** [Nosiphus/nosiphus-furniture#26]
In the 7-19 update for 1.20.1, I found that any block that should be broken by a pickaxe has no tool associated with it.  This problem did not occur with shovels or axes.

Rolling back to the 5-11 release fixed the problem, so it does not seem to cause any corruption in a saved world.

**Comment by Leafsong88** [comment]
Having the same issue i updated the mod today and now i can't use pickaxe on stone, cobblestone everyblock associated with a pickaxe. had to downgrade the mod

**Comment by seancrain** [comment]
I removed some legacy content a few days ago when I was working on the latest update, and I forgot to remove their corresponding entries from the pickaxe.json file. I shall correct this as soon as I can.

**Comment by seancrain** [comment]
This issue should be fixed with version 2024.07.21, which I have just uploaded to CurseForge. It may take some time for it to be processed in. Please let me know if it still seems to be having this issue.

**Comment by thomwoosley** [comment]
That seems to have fixed it.
