### ISSUE TITLE
Furniture disappears when broken

### ISSUE THREAD

**Issue by dittymargoo** [Nosiphus/nosiphus-furniture#4]
Mod version: nfm-2022.07.15-1.18.2.jar
Forge version: 40.1.67
Minecraft version: 1.18.2

If I place an item and then break/pick it up it disappears.  There's no crash log or problem other than I cannot pickup an item once it is placed.  At this point I've only tested this with the chairs, bathroom sink, bath, shower and toilet.  I have about 159 mods in my modpack.

I also want to thank you for making this mod.  I've missed these items for some time and was so pleased to find that someone had taken their time to 'reinstate' them into Minecraft's more current versions.  
Thanks again.

**Comment by seancrain** [comment]
This issue has been fixed in the 2022.08.29 release
