### ISSUE TITLE
[1.19.2 Forge] Every office chair except Yellow one are uncraftable 'cause no recipes.

### ISSUE THREAD

**Issue by RedBeast1959** [Nosiphus/nosiphus-furniture#5]
Forge: 1.19.2-forge-43.0.7
Mod: nfm-2022.07.15-1.19.jar

Like the title, Every office chair except Yellow variation are uncraftable. There are no recipes for them.
I checked with Just Enough Items mod and only office chairs don't have recipes. Every other item in this mod has recipes.

**Comment by seancrain** [comment]
This issue has been fixed in the 2022.08.29 release.
