### ISSUE TITLE
Oven not functional

### ISSUE THREAD

**Issue by KA3TBA** [Nosiphus/nosiphus-furniture#6]
Is the oven supposed to be a working piece of equipment. It is crafted with 8 pieces of concrete and a furnace, so I assumed it would function as a furnace, but when I click on it, it doesn't open up to the furnace interface.

**Comment by seancrain** [comment]
It will eventually be functional, yes. At the moment, I have focused on porting the block models over, so functionality hasn't been prioritized.

For the moment, it does not currently do anything.

**Comment by seancrain** [comment]
I have introduced functionality for the ovens for the 1.19.2 release today (March 21, 2023). I will be updating 1.19.3 in due course.
