### ISSUE TITLE
[1.19.2 Forge] Modern Kitchen Sink does not show water level unlike normal sink

### ISSUE THREAD

**Issue by RedBeast1959** [Nosiphus/nosiphus-furniture#8]
Forge 43.1.47
nfm-2022.10.27-1.19.jar

![2022-10-29_14 16 19](https://user-images.githubusercontent.com/100399264/198815300-627e5d48-a263-43a3-8c91-87464f5e5932.png)
( Sink - Modern Kitchen Sink - Kitchen Sink of original mod )

Like above screenshot, only modern kitchen sink doesn't show water level when pouring water with bucket.

**Comment by seancrain** [comment]
I have patched this with release 2022.11.23 which should be out later today.
